### ISSUE TITLE
Feature/dataflow branch fails to build on Ubuntu 17.10 since commit  2a68a52 threaded exec 

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#714]
Builds fine with previous commit including 2d28e0f926ddeac6aeecc2d4cd0ab452e5287c0b
Even with later libossia v3 commits.

Since 2a68a52248384615a1bda79cfab69497b702c85c
ninja returns "build stopped: subcommand failed"

In file included from /home/scrime/Documents/repos/score/base/plugins/score-plugin-engine/Engine/Executor/DocumentPlugin.cpp:26:0:
/home/scrime/Documents/repos/score/API/OSSIA/ossia/dataflow/graph/graph_parallel.hpp:2:10: fatal error: tbb/flow_graph.h: Aucun fichier ou dossier de ce type
 #include <tbb/flow_graph.h>

full output 

[408/525] Building CXX object base/plugins/score-plugin-engine/CM...iles/score_plugin_engine.dir/Engine/Executor/DocumentPlugin.cpp.o
FAILED: base/plugins/score-plugin-engine/CMakeFiles/score_plugin_engine.dir/Engine/Executor/DocumentPlugin.cpp.o 
/usr/bin/c++  -DASIO_STANDALONE=1 -DQT_CORE_LIB -DQT_DISABLE_DEPRECATED_BEFORE=0x050800 -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_QML_LIB -DQT_QUICK_LIB -DQT_SERIALPORT_LIB -DQT_STATICPLUGIN -DQT_SVG_LIB -DQT_WEBSOCKETS_LIB -DQT_WIDGETS_LIB -DRAPIDJSON_HAS_STDSTRING=1 -DSCORE_DEPLOYMENT_BUILD -DSCORE_LIB_BASE -DSCORE_LIB_DEVICE -DSCORE_LIB_INSPECTOR -DSCORE_LIB_PROCESS -DSCORE_LIB_STATE -DSCORE_PLUGIN_AUTOMATION -DSCORE_PLUGIN_CURVE -DSCORE_PLUGIN_DEVICEEXPLORER -DSCORE_PLUGIN_LOOP -DSCORE_PLUGIN_MAPPING -DSCORE_PLUGIN_SCENARIO -DSCORE_STATIC_PLUGINS -DTINYSPLINE_DOUBLE_PRECISION -Ibase/plugins/score-plugin-engine -I/home/scrime/Documents/repos/score/base/plugins/score-plugin-engine -Ibase/plugins/score-plugin-engine/score_plugin_engine_autogen/include -isystem /home/scrime/Documents/repos/boost_1_66_0 -I. -isystem /home/scrime/Documents/repos/score/API/3rdparty/variant/include -isystem /home/scrime/Documents/repos/score/API/3rdparty/nano-signal-slot -isystem /home/scrime/Documents/repos/score/API/3rdparty/brigand -isystem /home/scrime/Documents/repos/score/API/3rdparty/hopscotch-map/src -isystem /home/scrime/Documents/repos/score/API/3rdparty/readerwriterqueue -isystem /home/scrime/Documents/repos/score/API/3rdparty/exprtk -isystem /home/scrime/Documents/repos/score/3rdparty/miniz -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtSerialPort -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -Ibase/lib -I/home/scrime/Documents/repos/score/base/lib -isystem /home/scrime/Documents/repos/score/API/3rdparty/SmallFunction/smallfun/include -isystem /home/scrime/Documents/repos/score/API/3rdparty/asio/asio/include -isystem /home/scrime/Documents/repos/score/API/3rdparty/websocketpp -I/home/scrime/Documents/repos/score/API/OSSIA -IAPI/OSSIA -I/home/scrime/Documents/repos/score/API/3rdparty/nano-signal-slot/include -I/home/scrime/Documents/repos/score/API/3rdparty/spdlog/include -I/home/scrime/Documents/repos/score/API/3rdparty/brigand/include -I/home/scrime/Documents/repos/score/API/3rdparty/fmt -I/home/scrime/Documents/repos/score/API/3rdparty/chobo-shl/include -I/home/scrime/Documents/repos/score/API/3rdparty/frozen/include -I/home/scrime/Documents/repos/score/API/3rdparty/bitset2 -I/home/scrime/Documents/repos/score/API/3rdparty/GSL/include -I/home/scrime/Documents/repos/score/API/3rdparty/flat_hash_map -isystem /home/scrime/Documents/repos/score/API/3rdparty/rapidjson/include -isystem /home/scrime/Documents/repos/score/API/3rdparty/ModernMIDI -isystem /home/scrime/Documents/repos/score/API/3rdparty/ModernMIDI/third_party -isystem /home/scrime/Documents/repos/score/API/3rdparty/oscpack -isystem /usr/include/x86_64-linux-gnu/qt5/QtQml -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebSockets -isystem /usr/include/x86_64-linux-gnu/qt5/QtQuick -Ibase/plugins/score-lib-device -I/home/scrime/Documents/repos/score/base/plugins/score-lib-device -Ibase/plugins/score-lib-state -I/home/scrime/Documents/repos/score/base/plugins/score-lib-state -Ibase/plugins/score-lib-process -I/home/scrime/Documents/repos/score/base/plugins/score-lib-process -Ibase/plugins/score-lib-inspector -I/home/scrime/Documents/repos/score/base/plugins/score-lib-inspector -Ibase/plugins/score-plugin-scenario -I/home/scrime/Documents/repos/score/base/plugins/score-plugin-scenario -isystem /usr/include/x86_64-linux-gnu/qt5/QtSvg -I/home/scrime/Documents/repos/score/3rdparty/Qt-Color-Widgets -I3rdparty/Qt-Color-Widgets -Ibase/plugins/score-plugin-deviceexplorer -I/home/scrime/Documents/repos/score/base/plugins/score-plugin-deviceexplorer -Ibase/plugins/score-plugin-curve -I/home/scrime/Documents/repos/score/base/plugins/score-plugin-curve -Ibase/plugins/score-plugin-automation -I/home/scrime/Documents/repos/score/base/plugins/score-plugin-automation -Ibase/plugins/score-plugin-mapping -I/home/scrime/Documents/repos/score/base/plugins/score-plugin-mapping -Ibase/plugins/score-plugin-loop -I/home/scrime/Documents/repos/score/base/plugins/score-plugin-loop -O3 -march=native -std=c++1z -O3 -DNDEBUG -fPIC   -Wall -Wextra -Wno-unused-parameter -Wno-unknown-pragmas -Wno-four-char-constants -Wnon-virtual-dtor -pedantic -Woverloaded-virtual -pipe -Wno-missing-declarations -Werror=redundant-decls -Werror=return-type -Werror=trigraphs -Ofast -fno-finite-math-only -Wno-div-by-zero -Wsuggest-final-types -Wsuggest-final-methods -Wsuggest-override -Wpointer-arith -Wsuggest-attribute=noreturn -Wno-missing-braces -Wmissing-field-initializers -Wformat=2 -Wno-format-nonliteral -Wpedantic -Werror=return-local-addr -ffunction-sections -fdata-sections -Wl,--gc-sections -Winvalid-pch -include /home/scrime/Documents/repos/build-score/base/plugins/score-plugin-engine/cotire/score_plugin_engine_CXX_prefix.hxx -fPIC -std=gnu++1z -MD -MT base/plugins/score-plugin-engine/CMakeFiles/score_plugin_engine.dir/Engine/Executor/DocumentPlugin.cpp.o -MF base/plugins/score-plugin-engine/CMakeFiles/score_plugin_engine.dir/Engine/Executor/DocumentPlugin.cpp.o.d -o base/plugins/score-plugin-engine/CMakeFiles/score_plugin_engine.dir/Engine/Executor/DocumentPlugin.cpp.o -c /home/scrime/Documents/repos/score/base/plugins/score-plugin-engine/Engine/Executor/DocumentPlugin.cpp
In file included from /home/scrime/Documents/repos/score/base/plugins/score-plugin-engine/Engine/Executor/DocumentPlugin.cpp:26:0:
/home/scrime/Documents/repos/score/API/OSSIA/ossia/dataflow/graph/graph_parallel.hpp:2:10: fatal error: tbb/flow_graph.h: Aucun fichier ou dossier de ce type
 #include <tbb/flow_graph.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
[409/525] Building CXX object base/plugins/score-plugin-engine/CM...s/score_plugin_engine.dir/Engine/Executor/TimeSyncComponent.cpp.o
In file included from /home/scrime/Documents/repos/score/API/OSSIA/ossia/detail/logger.hpp:9:0,
                 from /home/scrime/Documents/repos/score/base/plugins/score-plugin-engine/Engine/Executor/TimeSyncComponent.cpp:16:
/home/scrime/Documents/repos/score/API/3rdparty/spdlog/include/spdlog/logger.h:25:7: warning: Declaring type ‘class spdlog::logger’ final would enable devirtualization of 2 calls [-Wsuggest-final-types]
 class logger
       ^~~~~~
In file included from /home/scrime/Documents/repos/score/API/3rdparty/spdlog/include/spdlog/logger.h:110:0,
                 from /home/scrime/Documents/repos/score/API/OSSIA/ossia/detail/logger.hpp:9,
                 from /home/scrime/Documents/repos/score/base/plugins/score-plugin-engine/Engine/Executor/TimeSyncComponent.cpp:16:
/home/scrime/Documents/repos/score/API/3rdparty/spdlog/include/spdlog/details/logger_impl.h:311:13: warning: Declaring method ‘virtual void spdlog::logger::_sink_it(spdlog::details::log_msg&)’ final would enable devirtualization of 1 call [-Wsuggest-final-methods]
 inline void spdlog::logger::_sink_it(details::log_msg& msg)
             ^~~~~~
/home/scrime/Documents/repos/score/API/3rdparty/spdlog/include/spdlog/details/logger_impl.h:338:13: warning: Declaring method ‘virtual void spdlog::logger::flush()’ final would enable devirtualization of 1 call [-Wsuggest-final-methods]
 inline void spdlog::logger::flush()
             ^~~~~~

**Comment by thibaudk** [comment]
after pulling commit 3862d782ff6299ce5703dca57819890ab1eec307
the build fails a couple steps earlier with the error 

In file included from /home/scrime/Documents/repos/score/base/plugins/score-plugin-engine/Engine/ApplicationPlugin.cpp:40:0:
/home/scrime/Documents/repos/score/base/plugins/score-plugin-engine/Engine/Executor/Settings/ExecutorModel.hpp:6:10: fatal error: QStringLiteral: Aucun fichier ou dossier de ce type
 #include <QStringLiteral>

full output

[397/522] Building CXX object base/plugins/score-plugin-engine/CMakeFiles/score_plugin_engine.dir/Engine/ApplicationPlugin.cpp.o
FAILED: base/plugins/score-plugin-engine/CMakeFiles/score_plugin_engine.dir/Engine/ApplicationPlugin.cpp.o 
/usr/bin/c++  -DASIO_STANDALONE=1 -DQT_CORE_LIB -DQT_DISABLE_DEPRECATED_BEFORE=0x050800 -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_NO_KEYWORDS -DQT_QML_LIB -DQT_QUICK_LIB -DQT_SERIALPORT_LIB -DQT_STATICPLUGIN -DQT_SVG_LIB -DQT_WEBSOCKETS_LIB -DQT_WIDGETS_LIB -DRAPIDJSON_HAS_STDSTRING=1 -DSCORE_DEPLOYMENT_BUILD -DSCORE_LIB_BASE -DSCORE_LIB_DEVICE -DSCORE_LIB_INSPECTOR -DSCORE_LIB_PROCESS -DSCORE_LIB_STATE -DSCORE_PLUGIN_AUTOMATION -DSCORE_PLUGIN_CURVE -DSCORE_PLUGIN_DEVICEEXPLORER -DSCORE_PLUGIN_LOOP -DSCORE_PLUGIN_MAPPING -DSCORE_PLUGIN_SCENARIO -DSCORE_STATIC_PLUGINS -DTINYSPLINE_DOUBLE_PRECISION -Ibase/plugins/score-plugin-engine -I/home/scrime/Documents/repos/score/base/plugins/score-plugin-engine -Ibase/plugins/score-plugin-engine/score_plugin_engine_autogen/include -isystem /home/scrime/Documents/repos/boost_1_66_0 -I. -isystem /home/scrime/Documents/repos/score/API/3rdparty/variant/include -isystem /home/scrime/Documents/repos/score/API/3rdparty/nano-signal-slot -isystem /home/scrime/Documents/repos/score/API/3rdparty/brigand -isystem /home/scrime/Documents/repos/score/API/3rdparty/hopscotch-map/src -isystem /home/scrime/Documents/repos/score/API/3rdparty/readerwriterqueue -isystem /home/scrime/Documents/repos/score/API/3rdparty/exprtk -isystem /home/scrime/Documents/repos/score/3rdparty/miniz -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtSerialPort -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -Ibase/lib -I/home/scrime/Documents/repos/score/base/lib -isystem /home/scrime/Documents/repos/score/API/3rdparty/SmallFunction/smallfun/include -isystem /home/scrime/Documents/repos/score/API/3rdparty/asio/asio/include -isystem /home/scrime/Documents/repos/score/API/3rdparty/websocketpp -I/home/scrime/Documents/repos/score/API/OSSIA -IAPI/OSSIA -I/home/scrime/Documents/repos/score/API/3rdparty/nano-signal-slot/include -I/home/scrime/Documents/repos/score/API/3rdparty/spdlog/include -I/home/scrime/Documents/repos/score/API/3rdparty/brigand/include -I/home/scrime/Documents/repos/score/API/3rdparty/fmt -I/home/scrime/Documents/repos/score/API/3rdparty/chobo-shl/include -I/home/scrime/Documents/repos/score/API/3rdparty/frozen/include -I/home/scrime/Documents/repos/score/API/3rdparty/bitset2 -I/home/scrime/Documents/repos/score/API/3rdparty/GSL/include -I/home/scrime/Documents/repos/score/API/3rdparty/flat_hash_map -isystem /home/scrime/Documents/repos/score/API/3rdparty/rapidjson/include -isystem /home/scrime/Documents/repos/score/API/3rdparty/ModernMIDI -isystem /home/scrime/Documents/repos/score/API/3rdparty/ModernMIDI/third_party -isystem /home/scrime/Documents/repos/score/API/3rdparty/oscpack -isystem /usr/include/x86_64-linux-gnu/qt5/QtQml -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebSockets -isystem /usr/include/x86_64-linux-gnu/qt5/QtQuick -Ibase/plugins/score-lib-device -I/home/scrime/Documents/repos/score/base/plugins/score-lib-device -Ibase/plugins/score-lib-state -I/home/scrime/Documents/repos/score/base/plugins/score-lib-state -Ibase/plugins/score-lib-process -I/home/scrime/Documents/repos/score/base/plugins/score-lib-process -Ibase/plugins/score-lib-inspector -I/home/scrime/Documents/repos/score/base/plugins/score-lib-inspector -Ibase/plugins/score-plugin-scenario -I/home/scrime/Documents/repos/score/base/plugins/score-plugin-scenario -isystem /usr/include/x86_64-linux-gnu/qt5/QtSvg -I/home/scrime/Documents/repos/score/3rdparty/Qt-Color-Widgets -I3rdparty/Qt-Color-Widgets -Ibase/plugins/score-plugin-deviceexplorer -I/home/scrime/Documents/repos/score/base/plugins/score-plugin-deviceexplorer -Ibase/plugins/score-plugin-curve -I/home/scrime/Documents/repos/score/base/plugins/score-plugin-curve -Ibase/plugins/score-plugin-automation -I/home/scrime/Documents/repos/score/base/plugins/score-plugin-automation -Ibase/plugins/score-plugin-mapping -I/home/scrime/Documents/repos/score/base/plugins/score-plugin-mapping -Ibase/plugins/score-plugin-loop -I/home/scrime/Documents/repos/score/base/plugins/score-plugin-loop -O3 -march=native -std=c++1z -O3 -DNDEBUG -fPIC   -Wall -Wextra -Wno-unused-parameter -Wno-unknown-pragmas -Wno-four-char-constants -Wnon-virtual-dtor -pedantic -Woverloaded-virtual -pipe -Wno-missing-declarations -Werror=redundant-decls -Werror=return-type -Werror=trigraphs -Ofast -fno-finite-math-only -Wno-div-by-zero -Wsuggest-final-types -Wsuggest-final-methods -Wsuggest-override -Wpointer-arith -Wsuggest-attribute=noreturn -Wno-missing-braces -Wmissing-field-initializers -Wformat=2 -Wno-format-nonliteral -Wpedantic -Werror=return-local-addr -ffunction-sections -fdata-sections -Wl,--gc-sections -Winvalid-pch -include /home/scrime/Documents/repos/build-score/base/plugins/score-plugin-engine/cotire/score_plugin_engine_CXX_prefix.hxx -fPIC -std=gnu++1z -MD -MT base/plugins/score-plugin-engine/CMakeFiles/score_plugin_engine.dir/Engine/ApplicationPlugin.cpp.o -MF base/plugins/score-plugin-engine/CMakeFiles/score_plugin_engine.dir/Engine/ApplicationPlugin.cpp.o.d -o base/plugins/score-plugin-engine/CMakeFiles/score_plugin_engine.dir/Engine/ApplicationPlugin.cpp.o -c /home/scrime/Documents/repos/score/base/plugins/score-plugin-engine/Engine/ApplicationPlugin.cpp
In file included from /home/scrime/Documents/repos/score/base/plugins/score-plugin-engine/Engine/ApplicationPlugin.cpp:40:0:
/home/scrime/Documents/repos/score/base/plugins/score-plugin-engine/Engine/Executor/Settings/ExecutorModel.hpp:6:10: fatal error: QStringLiteral: Aucun fichier ou dossier de ce type
 #include < QStringLiteral >
          ^~~~~~~~~~~~~~~~

**Comment by jcelerier** [comment]
QStringLiteral missing is certainly a problem of older qt version... which one is it that yo'ure using ? (apt-cache show qtbase5-dev)

**Comment by thibaudk** [comment]
I have qtbase5-dev version 5.9.1+dfsg-10ubuntu1.
Attempting to upgrade returns that this is the latest version.

**Comment by thibaudk** [comment]
The error was corrected with a fresh clone of score and a quick uninstall of Faust.
with Faust, the build stops at the very end when linking.
The Faust commit in question is the latest to this day 
2f0993e1874cdbba0ae8dbf7a5b36833cca52d87 

Score builds fine on this branch without it.

here is the full error log:

[534/534] Linking CXX executable score
FAILED: score 
: && /usr/bin/c++  -O3 -march=native -std=c++1z -O3 -DNDEBUG  -rdynamic base/app/CMakeFiles/score.dir/Application.cpp.o base/app/CMakeFiles/score.dir/main.cpp.o base/app/CMakeFiles/score.dir/score_autogen/mocs_compilation.cpp.o  -o score  base/lib/libscore_lib_base.a base/lib/libscore_lib_base.a /usr/lib/x86_64-linux-gnu/libQt5QuickControls2.so.5.9.1 base/plugins/score-plugin-pluginsettings/libscore_plugin_pluginsettings.a base/plugins/score-plugin-inspector/libscore_plugin_inspector.a base/plugins/score-plugin-deviceexplorer/libscore_plugin_deviceexplorer.a base/plugins/score-plugin-curve/libscore_plugin_curve.a base/plugins/score-plugin-automation/libscore_plugin_automation.a base/plugins/score-plugin-scenario/libscore_plugin_scenario.a base/plugins/score-plugin-loop/libscore_plugin_loop.a base/plugins/score-plugin-mapping/libscore_plugin_mapping.a base/plugins/score-plugin-engine/libscore_plugin_engine.a base/plugins/score-plugin-media/libscore_plugin_media.a base/plugins/score-plugin-fx/libscore_plugin_fx.a base/plugins/score-plugin-js/libscore_plugin_js.a base/plugins/score-plugin-midi/libscore_plugin_midi.a base/plugins/score-plugin-recording/libscore_plugin_recording.a base/addons/iscore-addon-shaders/libscore_addon_shader.a -Ofast -fno-finite-math-only -ffunction-sections -fdata-sections -Wl,--gc-sections -fuse-ld=gold -Wl,-z,defs -Wl,--threads -Wl,--thread-count,4 base/plugins/score-plugin-media/libscore_plugin_media.a -lavcodec -lavformat -lavutil -lswresample /usr/lib/liblilv-0.so -ldl /usr/local/lib/libfaust.a -ldl /usr/local/lib/libfaust.a -lssl -lcrypto -lcurses -lz -L/usr/lib/llvm-5.0/lib -lLLVM-5.0 base/plugins/score-plugin-engine/libscore_plugin_engine.a base/plugins/score-plugin-loop/libscore_plugin_loop.a base/plugins/score-plugin-scenario/libscore_plugin_scenario.a base/plugins/score-plugin-automation/libscore_plugin_automation.a 3rdparty/Qt-Color-Widgets/libColorWidgets-qt5.a base/plugins/score-plugin-mapping/libscore_plugin_mapping.a base/plugins/score-plugin-deviceexplorer/libscore_plugin_deviceexplorer.a 3rdparty/QProgressIndicator/libQProgressIndicator.a API/3rdparty/Servus/servus/libServusQt.a base/plugins/score-plugin-curve/libscore_plugin_curve.a base/plugins/score-lib-device/libscore_lib_device.a /usr/lib/x86_64-linux-gnu/libQt5Xml.so.5.9.1 base/plugins/score-lib-process/libscore_lib_process.a base/plugins/score-lib-inspector/libscore_lib_inspector.a base/plugins/score-lib-state/libscore_lib_state.a base/lib/libscore_lib_base.a API/OSSIA/libossia.a /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5.9.1 /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5.9.1 API/3rdparty/ModernMIDI/libModernMIDI.a -lasound -lpthread /usr/lib/x86_64-linux-gnu/libQt5WebSockets.so.5.9.1 /usr/lib/x86_64-linux-gnu/libQt5Network.so.5.9.1 API/3rdparty/Servus/servus/libServus.a -lavahi-common -lavahi-client -ldns_sd /usr/lib/x86_64-linux-gnu/libportaudio.a -ljack -lpthread -fvar-tracking-assignments -gdwarf-4 -Wl,--dynamic-list-cpp-new -Wl,--dynamic-list-cpp-typeinfo /usr/lib/x86_64-linux-gnu/libQt5Svg.so.5.9.1 3rdparty/QRecentFilesMenu/libQRecentFilesMenu.a /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5.9.1 /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5.9.1 /usr/lib/x86_64-linux-gnu/libQt5SerialPort.so.5.9.1 /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.9.1 -Ofast -fno-finite-math-only -ffunction-sections -fdata-sections -Wl,--gc-sections -fuse-ld=gold -Wl,-z,defs -Wl,--threads -Wl,--thread-count,4 && :
/usr/bin/ld.gold : erreur : -lcurses introuvable
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

**Comment by jcelerier** [comment]
> /usr/bin/ld.gold : erreur : -lcurses introuvable

means that you have to install libncurses5-dev

**Comment by thibaudk** [comment]
Yes this was it! Builds with Faust working at the latest commit.
Thanks a lot!
